version: "3.6"
services:
  1generator:
    image: "dargmuesli/1generator"
    deploy:
      labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:1generator.jonas-thelemann.test"
      - "traefik.port=80"
  adminer:
    image: "adminer"
    deploy:
      labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:adminer.jonas-thelemann.test"
      - "traefik.port=8080"
    volumes:
    - "./production/adminer/adminer.css:/var/www/html/adminer.css"
  jonas-thelemann-de:
    image: "dargmuesli/jonas-thelemann.de:test"
    deploy:
      labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:jonas-thelemann.test,www.jonas-thelemann.test"
      - "traefik.port=443"
      - "traefik.protocol=https"
    volumes:
    - "../jonas-thelemann.de/dist/jonas-thelemann.de:/var/www/jonas-thelemann.de"
    - "./development/certificates:/etc/ssl/certificates"
  randomwinpicker-de:
    image: "dargmuesli/randomwinpicker"
    deploy:
      labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:randomwinpicker.jonas-thelemann.test"
      - "traefik.port=443"
      - "traefik.protocol=https"
    volumes:
    - "./development/certificates/jonas-thelemann.de.crt:/etc/ssl/certificates/randomwinpicker.crt"
    - "./development/certificates/jonas-thelemann.de.key:/etc/ssl/certificates/randomwinpicker.key"
  postgres:
    image: "postgres:alpine"
    environment:
      POSTGRES_ADDITIONAL_DBS: "randomwinpicker"
      POSTGRES_DB_FILE: "/run/secrets/postgres_db"
      POSTGRES_PASSWORD_FILE: "/run/secrets/postgres_password"
      POSTGRES_USER_FILE: "/run/secrets/postgres_user"
    secrets:
    - "postgres_db"
    - "postgres_password"
    - "postgres_user"
    volumes:
    - "postgres-data:/var/lib/postgresql/data"
    - "./production/postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/"
  traefik:
    image: "traefik"
    ports:
    - target: 80
      published: 80
      protocol: "tcp"
      mode: "host"
    - target: 443
      published: 443
      protocol: "tcp"
      mode: "host"
    deploy:
      labels:
      - "traefik.docker.network=jonas-thelemann-de_default"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:traefik.jonas-thelemann.test"
      - "traefik.port=8080"
      mode: "global"
      placement:
        constraints:
        - "node.role == manager"
    command:
    - "--api"
    - "--defaultentrypoints=http,https"
    - "--docker"
    - "--docker.domain=jonas-thelemann.de"
    - "--docker.exposedByDefault=false"
    - "--docker.swarmMode=true"
    - "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https"
    - "--entryPoints=Name:https Address::443 TLS:/etc/ssl/certificates/jonas-thelemann.de.crt,/etc/ssl/certificates/jonas-thelemann.de.key Compress:true"
    - "--insecureSkipVerify=true"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "./development/certificates:/etc/ssl/certificates"
secrets:
  postgres_db:
    file: "./development/secrets/postgres_db.secret"
  postgres_password:
    file: "./development/secrets/postgres_password.secret"
  postgres_user:
    file: "./development/secrets/postgres_user.secret"
volumes:
  postgres-data: {}
