# jonas-thelemann.de
# https://jonas-thelemann.de/
# jonas-thelemann
# https://github.com/dargmuesli/jonas-thelemann/
---
configs:
  creal_strapi_env:
  # The DJ website's CMS environment variables.
    file: ./secrets/creal_strapi/env.secret
secrets:
  codimd_db_url:
  # The markdown collaboration tool's database url.
    file: ./secrets/codimd/db_url.secret
  codimd_session-secret:
  # The markdown collaboration tool's session secret.
    file: ./secrets/codimd/session-secret.secret
  creal_aws-bucket:
  # The DJ website's AWS bucket name.
    file: ./secrets/creal/aws-bucket.secret
  creal_aws-credentials:
  # The DJ website's AWS credentials.
    file: ./secrets/creal/aws-credentials.secret
  creal_sqitch-target:
  # The DJ website's Sqitch target.
    file: ./secrets/creal/sqitch-target.secret
  nextcloud_admin-password:
  # The cloud admin user's password.
    file: ./secrets/nextcloud/admin-password.secret
  nextcloud_admin-user:
  # The cloud admin user's name.
    file: ./secrets/nextcloud/admin-user.secret
  portainer_admin-password:
  # The container manager's password for the user `admin`.
    file: ./secrets/portainer/admin-password.secret
  postgres-backup_db:
  # The database backup service's database name.
    file: ./secrets/postgres-backup/db.secret
  postgres_db:
  # The database's name.
    file: ./secrets/postgres/db.secret
  postgres_password:
  # The database default user's password.
    file: ./secrets/postgres/password.secret
  postgres_role_creal-postgraphile_password:
  # The `creal_postgraphile` database role's password.
    file: ./secrets/postgres/role_creal-postgraphile_password.secret
  postgres_user:
  # The database default user's name.
    file: ./secrets/postgres/user.secret
services:
  1generator:
  # You can access this subproject at [1generator.jonas-thelemann.test](https://1generator.jonas-thelemann.test/).
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.1generator.middlewares=redirectscheme
      - traefik.http.routers.1generator.rule=Host(`1generator.${STACK_DOMAIN}`)
      - traefik.http.routers.1generator_secure.rule=Host(`1generator.${STACK_DOMAIN}`)
      - traefik.http.routers.1generator_secure.tls.options=mintls13@file #DARGSTACK-REMOVE
      - traefik.http.services.1generator.loadbalancer.server.port=80
    image: dargmuesli/1generator:1.0.1@sha256:6f8dc24e6fc0a254ebe65b0d49f61fdf0749836b91ce1fd3314bbf92ced2b07c
  adminer:
  # You can access the database's frontend at [adminer.jonas-thelemann.test](https://adminer.jonas-thelemann.test/).
  # This information is required for login:
  #
  # |          |                     |
  # | -------- | ------------------- |
  # | System   | PostgreSQL          |
  # | Server   | postgres            |
  # | Username | [postgres_user]     |
  # | Password | [postgres_password] |
  # | Database | [postgres_db]       |
  #
  # Values in square brackets are [Docker secrets](https://docs.docker.com/engine/swarm/secrets/).
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.adminer.middlewares=redirectscheme
      - traefik.http.routers.adminer.rule=Host(`adminer.${STACK_DOMAIN}`)
      - traefik.http.routers.adminer_secure.rule=Host(`adminer.${STACK_DOMAIN}`)
      - traefik.http.routers.adminer_secure.tls.options=mintls13@file #DARGSTACK-REMOVE
      - traefik.http.services.adminer.loadbalancer.server.port=8080
    image: adminer:4.7.8-standalone@sha256:c983c4eeee89a3cd6e10695e1a04e8d6fedf9adeef8ea3ae5e8125fe21845d76
    volumes:
    - ../production/configuration/adminer/adminer.css:/var/www/html/adminer.css:ro
  codimd:
  # You can access the markdown collaboration tool at [codimd.jonas-thelemann.test](https://codimd.jonas-thelemann.test/).
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.codimd.middlewares=redirectscheme
      - traefik.http.routers.codimd.rule=Host(`codimd.${STACK_DOMAIN}`)
      - traefik.http.routers.codimd_secure.rule=Host(`codimd.${STACK_DOMAIN}`)
      - traefik.http.routers.codimd_secure.tls.options=mintls13@file #DARGSTACK-REMOVE
      - traefik.http.services.codimd.loadbalancer.server.port=3000
    environment:
      CMD_DOMAIN: codimd.${STACK_DOMAIN}
      CMD_PROTOCOL_USESSL: "true"
      CMD_URL_ADDPORT: "false"
    image: quay.io/codimd/server:1.6.0-alpine@sha256:4957009ea9bcb32c94865530e439c4adfe1a6fdc56a09b9b0743af69224f165b
    secrets:
    - source: codimd_db_url
      target: dbURL
    - source: codimd_session-secret
      target: sessionsecret
  creal:
  # You can access the DJ website at [creal.jonas-thelemann.test](https://creal.jonas-thelemann.test/).
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.creal.middlewares=redirectscheme
      - traefik.http.routers.creal.rule=Host(`creal.${STACK_DOMAIN}`)
      - traefik.http.routers.creal_secure.rule=Host(`creal.${STACK_DOMAIN}`)
      - traefik.http.routers.creal_secure.tls.options=mintls13@file #DARGSTACK-REMOVE
      - traefik.http.services.creal.loadbalancer.server.port=3000
    environment:
      AWS_SHARED_CREDENTIALS_FILE: /run/secrets/creal_aws-credentials
      NUXT_ENV_STACK_DOMAIN: ${STACK_DOMAIN} # Must be prefixed by "NUXT_ENV_" (https://nuxtjs.org/api/configuration-env/#automatic-injection-of-environment-variables)
    image: dargmuesli/creal:dev
    secrets:
    - creal_aws-bucket
    - creal_aws-credentials
    - creal_sqitch-target
    - postgres_role_creal-postgraphile_password
    user: node:node
    volumes:
    - ../../../creal/nuxt/:/srv/app/
    - ../../../creal/sqitch/:/srv/sqitch/
  creal_strapi:
  # You can access the DJ website's CMS at [strapi.jonas-thelemann.test](https://strapi.jonas-thelemann.test/).
    configs:
    - source: creal_strapi_env
      target: /srv/app/.env
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.creal_strapi.middlewares=redirectscheme
      - traefik.http.routers.creal_strapi.rule=Host(`strapi.${STACK_DOMAIN}`)
      - traefik.http.routers.creal_strapi_secure.rule=Host(`strapi.${STACK_DOMAIN}`)
      - traefik.http.routers.creal_strapi_secure.tls.options=mintls13@file #DARGSTACK-REMOVE
      - traefik.http.services.creal_strapi.loadbalancer.server.port=1337
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: creal_strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
    image: strapi/strapi:3.3.4@sha256:f099b248c34c5296f14225c29a80290a33c82bc6057a7669ae8fd91b03cf323c
    secrets:
    - postgres_password
    - postgres_user
    volumes:
    - ../../../creal_strapi/:/srv/app/
  jonas-thelemann:
  # You can access the main project via `jonas-thelemann_nginx`.
    image: dargmuesli/jonas-thelemann:dev
    user: 1000:82
    volumes:
    - ../../../jonas-thelemann/dist/jonas-thelemann/server/:/var/www/jonas-thelemann/server/
    - ../production/secrets/jonas-thelemann/jonas-thelemann.env:/var/www/jonas-thelemann/credentials/jonas-thelemann.env:ro
  jonas-thelemann_nginx:
  # You can access the main project at [jonas-thelemann.test](https://jonas-thelemann.test/).
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.jonas-thelemann_nginx.middlewares=redirectscheme
      - traefik.http.routers.jonas-thelemann_nginx.rule=Host(`${STACK_DOMAIN}`, `www.${STACK_DOMAIN}`)
      - traefik.http.routers.jonas-thelemann_nginx_secure.rule=Host(`${STACK_DOMAIN}`, `www.${STACK_DOMAIN}`)
      - traefik.http.routers.jonas-thelemann_nginx_secure.tls.options=mintls13@file #DARGSTACK-REMOVE
      - traefik.http.routers.jonas-thelemann_nginx_secure_tools.rule=Host(`${STACK_DOMAIN}`, `www.${STACK_DOMAIN}`) && PathPrefix(`/tools/`)
      - traefik.http.routers.jonas-thelemann_nginx_secure_tools.tls.options=mintls13@file #DARGSTACK-REMOVE
      - traefik.http.services.jonas-thelemann_nginx.loadbalancer.server.port=80
    image: nginx:1.19.5-alpine@sha256:6ceeeab513f7d15cea38c1f8dfe5455323b5a1bfd568516b3b0ee70406f75247
    volumes:
    - ../production/configuration/jonas-thelemann_nginx/nginx.conf:/etc/nginx/nginx.conf
    - ../../../jonas-thelemann/dist/jonas-thelemann/server/:/var/www/jonas-thelemann/server/:ro
    - ./certificates/:/etc/ssl/certificates/
  nextcloud:
  # You can access nextcloud via `nextcloud_nginx`.
    env_file: ../production/secrets/nextcloud/nextcloud.env
    image: nextcloud:20.0.3-fpm-alpine@sha256:c07b955ac7ee0e1d0a374d594e80a0114357c7da71f22da77b4f3f7ddbac668a
    secrets:
    - nextcloud_admin-password
    - nextcloud_admin-user
    - postgres_password
    - postgres_user
    volumes:
    - nextcloud_data:/var/www/html/
  nextcloud_nginx:
  # You can access nexcloud's frontend at [nextcloud.jonas-thelemann.test](https://nextcloud.jonas-thelemann.test/).
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.middlewares.nextcloud_nginx_secure_redirectregex_calendar.redirectregex.regex=.*
      - traefik.http.middlewares.nextcloud_nginx_secure_redirectregex_calendar.redirectregex.replacement=https://nextcloud.${STACK_DOMAIN}/apps/calendar/
      - traefik.http.middlewares.nextcloud_nginx_secure_redirectregex_contacts.redirectregex.regex=.*
      - traefik.http.middlewares.nextcloud_nginx_secure_redirectregex_contacts.redirectregex.replacement=https://nextcloud.${STACK_DOMAIN}/apps/contacts/
      - traefik.http.routers.nextcloud_nginx.middlewares=redirectscheme
      - traefik.http.routers.nextcloud_nginx.rule=Host(`nextcloud.${STACK_DOMAIN}`)
      - traefik.http.routers.nextcloud_nginx_secure.rule=Host(`nextcloud.${STACK_DOMAIN}`)
      - traefik.http.routers.nextcloud_nginx_secure.tls.options=mintls13@file #DARGSTACK-REMOVE
      - traefik.http.routers.nextcloud_nginx_secure_calendar.middlewares=nextcloud_nginx_secure_redirectregex_calendar@docker
      - traefik.http.routers.nextcloud_nginx_secure_calendar.rule=Host(`calendar.${STACK_DOMAIN}`)
      - traefik.http.routers.nextcloud_nginx_secure_calendar.tls.options=mintls13@file #DARGSTACK-REMOVE
      - traefik.http.routers.nextcloud_nginx_secure_contacts.middlewares=nextcloud_nginx_secure_redirectregex_contacts@docker
      - traefik.http.routers.nextcloud_nginx_secure_contacts.rule=Host(`contacts.${STACK_DOMAIN}`)
      - traefik.http.routers.nextcloud_nginx_secure_contacts.tls.options=mintls13@file #DARGSTACK-REMOVE
      - traefik.http.services.nextcloud.loadbalancer.server.port=80
    image: nginx:1.19.5-alpine@sha256:6ceeeab513f7d15cea38c1f8dfe5455323b5a1bfd568516b3b0ee70406f75247
    volumes:
    - ../production/configuration/nextcloud_nginx/nginx.conf:/etc/nginx/nginx.conf
    - nextcloud_data:/var/www/html/
  portainer:
  # You can access the container manager's frontend at [portainer.jonas-thelemann.test](https://portainer.jonas-thelemann.test/).
    command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify --admin-password-file '/run/secrets/portainer_admin-password'
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.middlewares=redirectscheme
      - traefik.http.routers.portainer.rule=Host(`portainer.${STACK_DOMAIN}`)
      - traefik.http.routers.portainer_secure.rule=Host(`portainer.${STACK_DOMAIN}`)
      - traefik.http.routers.portainer_secure.tls.options=mintls13@file #DARGSTACK-REMOVE
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: portainer/portainer:1.24.1@sha256:02c51e3116cddbeff35da5a968ce909fcb07ff1b9688faa2eaaa2c237e9f7548
    secrets:
    - portainer_admin-password
    volumes:
    - portainer_data:/data
  portainer-agent:
  # You can access the container manager agent via `portainer`.
    deploy:
      mode: global
      placement:
        constraints:
        - node.platform.os == linux
    environment:
      AGENT_CLUSTER_ADDR: tasks.portainer-agent
    image: portainer/agent:1.6.1@sha256:390289880d65315bf348ccf1b0eb514f83a5e1dab399e8365b69740c42f8eeaa
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/docker/volumes:/var/lib/docker/volumes
  postgres:
  # You can access the database via `adminer`.
    environment:
      POSTGRES_ADDITIONAL_DBS: codimd creal creal_strapi nextcloud randomwinpicker
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER_FILE: /run/secrets/postgres_user
    image: postgres:13.1-alpine@sha256:024c97d18e5060ef48ce20ea96550506a137403b0aaf1d2fd56b1483d40b89fe
    secrets:
    - postgres_db
    - postgres_password
    - postgres_user
    volumes:
    - /mnt/dev/postgresql/:/var/run/postgresql/ #DARGSTACK-REMOVE
    - postgres_data:/var/lib/postgresql/data/
    - ../production/configuration/postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/:ro
  randomwinpicker:
  # You can access the main project via `randomwinpicker_nginx`.
    image: dargmuesli/randomwinpicker:5.1.8@sha256:1e7d9a76caccb3b519f3d3fdd8b4b906e5cf0f01d69dbcbd25b6fb7fafb086e3
    volumes:
    - randomwinpicker_data:/var/www/randomwinpicker/server/
    - ../production/secrets/randomwinpicker/randomwinpicker.env:/var/www/randomwinpicker/credentials/randomwinpicker.env:ro
  randomwinpicker_nginx:
  # You can access the main project at [randomwinpicker.jonas-thelemann.test](https://randomwinpicker.jonas-thelemann.test/).
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.randomwinpicker_nginx.middlewares=redirectscheme
      - traefik.http.routers.randomwinpicker_nginx.rule=Host(`randomwinpicker.${STACK_DOMAIN}`)
      - traefik.http.routers.randomwinpicker_nginx_secure.rule=Host(`randomwinpicker.${STACK_DOMAIN}`)
      - traefik.http.routers.randomwinpicker_nginx_secure.tls.options=mintls13@file #DARGSTACK-REMOVE
      - traefik.http.services.randomwinpicker_nginx.loadbalancer.server.port=80
    image: nginx:1.19.5-alpine@sha256:6ceeeab513f7d15cea38c1f8dfe5455323b5a1bfd568516b3b0ee70406f75247
    volumes:
    - randomwinpicker_data:/var/www/randomwinpicker/server/:ro
    - ../production/configuration/randomwinpicker_nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./certificates/:/etc/ssl/certificates/
  thelounge:
  # You can access the web IRC client's dashboard at [thelounge.jonas-thelemann.test](https://traefik.jonas-thelemann.test/).
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.thelounge.middlewares=redirectscheme
      - traefik.http.routers.thelounge.rule=Host(`thelounge.${STACK_DOMAIN}`)
      - traefik.http.routers.thelounge_secure.rule=Host(`thelounge.${STACK_DOMAIN}`)
      - traefik.http.routers.thelounge_secure.tls.options=mintls13@file #DARGSTACK-REMOVE
      - traefik.http.services.thelounge.loadbalancer.server.port=9000
    image: thelounge/thelounge:4.2.0-alpine@sha256:43148f2363b14932e3b09fcb153bb696bce3ca5721c1e65d211e5eb004e62697
    volumes:
    - thelounge_data:/var/opt/thelounge
  traefik:
  # You can access the reverse proxy's dashboard at [traefik.jonas-thelemann.test](https://traefik.jonas-thelemann.test/).
  # Traefik enables HTTPS for all services and acts as a load-balancer too.
    command:
    - --api=true
    - --entryPoints.web.address=:80
    - --entryPoints.web-secure.address=:443
    - --pilot.token=${TRAEFIK_PILOT_TOKEN}
    - --providers.docker=true
    - --providers.docker.endpoint=unix:///var/run/docker.sock
    - --providers.docker.exposedByDefault=false
    - --providers.docker.swarmMode=true
    - --providers.file.filename=/dynamic.yml #DARGSTACK-REMOVE
    - --providers.file.watch=true #DARGSTACK-REMOVE
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.middlewares.redirectscheme.redirectscheme.scheme=https
      - traefik.http.routers.traefik.middlewares=redirectscheme
      - traefik.http.routers.traefik.rule=Host(`traefik.${STACK_DOMAIN}`)
      - traefik.http.routers.traefik_secure.rule=Host(`traefik.${STACK_DOMAIN}`)
      - traefik.http.routers.traefik_secure.service=api@internal
      - traefik.http.routers.traefik_secure.tls.options=mintls13@file #DARGSTACK-REMOVE
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      mode: global
      placement:
        constraints:
        - node.role == manager
    image: traefik:2.3.5@sha256:1d78768498478b46ad6bf3d33a1af588767ce33a56f906a4dcf77eb7b93c595c
    ports:
    - mode: host
      protocol: tcp
      published: 80
      target: 80
    - mode: host
      protocol: tcp
      published: 443
      target: 443
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./certificates/:/etc/traefik/acme/
    - ./configurations/traefik/dynamic.yml:/dynamic.yml:ro #DARGSTACK-REMOVE
version: "3.6"
volumes:
  nextcloud_data:
  # The cloud's data.
    {}
  portainer_data:
  # The container manager's data.
    {}
  postgres_data:
  # The database's data.
    {}
  randomwinpicker_data:
  # Randomwinpicker's data.
    {}
  thelounge_data:
  # The IRC client's data.
    {}
