secrets:
  traefik_cf-api-email:
    external: true
  traefik_cf-api-key:
    external: true
services:
  certdumper:
    image: alpine:latest
    command: >
      ash -c " \
        apk --no-cache add inotify-tools jq openssl util-linux bash && \
        cd /etc/traefik/acme/ && \
        wget https://raw.githubusercontent.com/containous/traefik/master/contrib/scripts/dumpcerts.sh -O ./dumpcerts.sh && \
        chmod 744 dumpcerts.sh && \
        while true; do \
          bash dumpcerts.sh acme.json ./ && \
          ln -f ./certs/$${STACK_DOMAIN}.crt ./$${STACK_DOMAIN%.*}.crt && \
          ln -f ./private/$${STACK_DOMAIN}.key ./$${STACK_DOMAIN%.*}.key && \
          ln -f ./$${STACK_DOMAIN%.*}.crt ./randomwinpicker.crt && \
          ln -f ./$${STACK_DOMAIN%.*}.key ./randomwinpicker.key && \
          inotifywait -e modify ./acme.json
        done"
    environment:
      STACK_DOMAIN: ${STACK_DOMAIN}
    volumes:
    - acme_data:/etc/traefik/acme/
  randomwinpicker:
    volumes:
    - (( replace ))
    - ./secrets/randomwinpicker.env:/var/www/randomwinpicker/credentials/randomwinpicker.env:ro
    - acme_data:/etc/ssl/certificates/
  traefik:
    command:
    - (( prepend ))
    - --acme.acmeLogging=true
    - --acme.dnsChallenge.provider=${STACK_ACME_PROVIDER}
    - --acme.domains=${STACK_DOMAIN},1generator.${STACK_DOMAIN},adminer.${STACK_DOMAIN},nextcloud.${STACK_DOMAIN},randomwinpicker.${STACK_DOMAIN},traefik.${STACK_DOMAIN},www.${STACK_DOMAIN}
    - --acme.email=${STACK_ACME_EMAIL}
    - --acme.entrypoint=https
    - --acme.storage=/etc/traefik/acme/acme.json
    environment:
      # For other providers see:
      # https://docs.traefik.io/configuration/acme/#provider
      CF_API_EMAIL_FILE: /run/secrets/traefik_cf-api-email
      CF_API_KEY_FILE: /run/secrets/traefik_cf-api-key
    secrets:
    - traefik_cf-api-email
    - traefik_cf-api-key
    volumes:
    - (( replace ))
    - /var/run/docker.sock:/var/run/docker.sock
    - acme_data:/etc/traefik/acme/
  www:
    volumes:
    - (( replace ))
    - ./secrets/jonas-thelemann.env:/var/www/jonas-thelemann/credentials/jonas-thelemann.env:ro
    - acme_data:/etc/ssl/certificates/
volumes:
  acme_data: {}
