secrets:
  traefik_cf-dns-api-token:
    external: true
  traefik_cf-zone-api-token:
    external: true
services:
  1generator:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.1generator_secure.tls.certresolver=default
  adminer:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.adminer_secure.middlewares=auth
      - traefik.http.routers.adminer_secure.tls.certresolver=default
  codimd:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.codimd_secure.tls.certresolver=default
  creal:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.creal_secure.tls.certresolver=default
    image: dargmuesli/creal:0.1.6@sha256:ef3694b00f8c4d2b1c4b6d1ff608850ab9ae146901e1fe48c2783d6d29cb17b7
    user: (( prune ))
    volumes: (( prune ))
  creal_strapi:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.creal_strapi_secure.tls.certresolver=default
    image: dargmuesli/creal_strapi:1.0.1@sha256:a7096f7641fbba39f9bff6da1fc21f9fad510a819f75102890c918228d4347bb
    volumes:
    - creal_strapi_data:/srv/app/
  jonas-thelemann:
    image: dargmuesli/jonas-thelemann:3.3.0@sha256:7fa864c5202af55484bc83111132cf320a7a367c847fc4c7a8cde58d9cd235c2
    user: (( prune ))
    volumes:
    - (( replace ))
    - ./secrets/jonas-thelemann/jonas-thelemann.env:/var/www/jonas-thelemann/credentials/jonas-thelemann.env:ro
    - jonas-thelemann_data:/var/www/jonas-thelemann/server/
    - acme_data:/etc/ssl/certificates/
  jonas-thelemann_nginx:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.jonas-thelemann_nginx_secure.tls.certresolver=default
      - traefik.http.routers.jonas-thelemann_nginx_secure_tools.middlewares=auth
      - traefik.http.routers.jonas-thelemann_nginx_secure_tools.tls.certresolver=default
    volumes:
    - (( replace ))
    - ./configuration/jonas-thelemann_nginx/nginx.conf:/etc/nginx/nginx.conf
    - jonas-thelemann_data:/var/www/jonas-thelemann/server/:ro
    - acme_data:/etc/ssl/certificates/
  nextcloud_nginx:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.nextcloud_nginx_secure.tls.certresolver=default
      - traefik.http.routers.nextcloud_nginx_secure_calendar.tls.certresolver=default
      - traefik.http.routers.nextcloud_nginx_secure_contacts.tls.certresolver=default
  portainer:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.portainer_secure.tls.certresolver=default
  randomwinpicker_nginx:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.randomwinpicker_nginx_secure.tls.certresolver=default
  thelounge:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.thelounge_secure.tls.certresolver=default
  traefik:
    command:
    - (( prepend ))
    - --certificatesResolvers.default.acme.email=${STACK_ACME_EMAIL}
    - --certificatesResolvers.default.acme.storage=/etc/traefik/acme/acme.json
    - --certificatesResolvers.default.acme.dnsChallenge.provider=${STACK_ACME_PROVIDER}
    deploy:
      labels:
      - (( append ))
      - traefik.http.middlewares.auth.basicauth.users=${STACK_AUTH_BASIC}
      - traefik.http.routers.traefik_secure.middlewares=auth
      - traefik.http.routers.traefik_secure.tls.certresolver=default
    environment:
      CF_DNS_API_TOKEN_FILE: /run/secrets/traefik_cf-dns-api-token
      CF_ZONE_API_TOKEN_FILE: /run/secrets/traefik_cf-zone-api-token
    secrets:
    - traefik_cf-dns-api-token
    - traefik_cf-zone-api-token
  traefik_certs-dumper:
    command:
    - file
    - --clean=false
    - --crt-name="$STACK_DOMAIN"
    - --dest=/etc/traefik/acme/
    - --key-name="$STACK_DOMAIN"
    - --source=/etc/traefik/acme/acme.json
    - --version=v2
    - --watch
    environment:
      STACK_DOMAIN: ${STACK_DOMAIN}
    image: ldez/traefik-certs-dumper:v2.7.0@sha256:63614a85fe984b62716c638bca1a0a837e86f7249ef3c0e7f9db8a1fed743c96
    volumes:
    - acme_data:/etc/traefik/acme/
volumes:
  acme_data: {}
  jonas-thelemann_data: {}
